name: modelo-imagen-api
services:
- name: web
  dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
  http_port: 8080
  instance_count: 1
  instance_size_slug: professional-xs
  envs:
  - key: PYTHONUNBUFFERED
    value: "1"
  - key: PYTHONDONTWRITEBYTECODE
    value: "1"
