name: modelo-imagen-api
services:
- name: web
  environment_slug: python
  github:
    branch: main
    deploy_on_push: true
  run_command: uvicorn app:app --host 0.0.0.0 --port 8080
  http_port: 8080
  instance_count: 1
  instance_size_slug: professional-xs
  envs:
  - key: PYTHONUNBUFFERED
    value: "1"
  - key: PYTHONDONTWRITEBYTECODE
    value: "1"
